### ISSUE TITLE
Question about CSRF Token in SPA

### ISSUE THREAD

**Issue by jk31** [duplxey/django-spa-cookie-auth#4]
Hello,

I'm following your wonderful tutorial (https://testdriven.io/blog/django-spa-auth/) about session-based authentication with django backends in single-page applications (in my case vue).

I'm especially interested in the case of separated frontend/backend with cross-origin.

The only thing that is problematic to me is the way how the csrf token is requested from the frontend.

According to the tutorial, the frontend runs `getSession` when the main component is mounted. This function verifies the authentication session to the backend, If there is no authentication session, the frontend also requests the csrf token and saves it to the state, as it is needed for the login request. What I don't understand is why the frontend doesn't request the csrf token if the user is already authenticated. If you close the page and return later, your authentication session will be active (what I want), but the csrf token from the state will be gone, which is probably needed for other requests. 

Therefore I think that when the main component is mounted, the frontend should also request the csrf token and save it to the state/store. 

This is my first SPA project and your tutorial helped me a lot. I hope that you can clarify my concerns.

**Comment by duplxey** [comment]
You only have to pass the CSRF token when submitting forms (so POST requests). This is why we only fetch the CSRF token if the user is not authenticated, because we need in in order to log the user in.

In a real life application you should fetch a new CSRF token every time you need it. If you use the same one over and over again you can expose yourself to BREACH attacks. (Learn more about it here: https://www.sjoerdlangkemper.nl/2019/12/18/different-csrf-token-for-each-form/)

**Comment by duplxey** [comment]
I'm closing the issue, if you have any other questions open a new one.
